config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    get "delete"
  end
  get 'expenses/index'

  get 'expenses/new'

  get 'expenses/new'

  get 'expense/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'account_activations/edit'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'members#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :members do
    collection do 
      get :search
      # get :search, :action => 'search_post', :as => 'search_post'
      # get 'search/:q', :action => 'search', :as => 'search'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :incomes do 
    get "delete"
  end
  resources :expenses do 
    get "delete"
  end
  resources :categories do 
    get "delete"
  end
  resources :reminders do
   get "delete"
 end
 

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :member
	has_many :incomes, dependent: :destroy
	has_many :expenses, dependent: :destroy
validates :title, uniqueness: {scope: :member_id}
	validates :title, presence: true
	validates :member_id, presence: true
	# validates :description, presence: true
	# validates :amount, presence: true
	# validates :date, presence: true
	
  # def self.total_on(date)
  # 	where("date(date) = ?", date).sum(:amount)
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


	def index
		@categories = Category.where(member_id: current_member.id)
		respond_to do |format|
	      format.html # renders index.html.erb
	      format.js # renders index.js.erb
    	end
	end

	def new
		@category = Category.new
	end

	def create
		@categories = Category.all	
		@category = Category.create(category_params.merge(member_id: current_member.id))
		
	end

	def show
		@category = Category.find(params[:id])
		@category_data=(@category.expenses + @category.incomes).sort{|a,b| a.date <=> b.date }

	end

	def edit
		@category = Category.find(params[:id])
	end


	def delete
		@category = Category.find(params[:category_id])
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		# redirect_to categories_path
	end

	private 
  	def category_params
  		params.require(:category).permit(:title)
  	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr id="category-<%= category.id%>">
				<td><%= category.title %></td>
						<td><%= category.description %></td>
						
						<td><%= link_to "Edit", edit_category_path(category), 
										remote: true, class: 'btn btn-default' %></td>
						<td><%= link_to "Delete", category_delete_path(category), remote: true, class: 'btn btn-danger' %></td>
					</tr>

app/views/categories/_delete.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h3>Delete Expense</h3>
		</div>

		<div class="modal-body">
			<ul class="errors"></ul>
			Are you sure you want to delete <b><%= @category.title%></b>
			 along with its associated transactions.
		</div>

		<div class="modal-footer">
			<%= link_to "Yes, Delete This Expense", category_path(@category), method: :delete, remote: true, class: 'btn btn-danger' %>
			<%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
		</div>
	</div>
</div>

app/views/categories/_edit.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h3><%= "Editing #{@category.title}" %></h3>
		</div>
		<%= render "form" %>
	</div>
</div>	
		

app/views/categories/_form.html.erb
		<%= form_for @category, remote: true, html: { style: "display:inline" } do |f| %>
			<div class="modal-body">
				<ul class="errors"></ul>
			
				<div class="form-group">
					<%= f.label :title, class: 'control-label' %>
					<%= f.text_field :title, class: 'form-control' %>
				</div>

			
			</div>

			<div class="modal-footer">
				<%= f.submit "Add Tag", class: 'btn sign-up' %>
				<%= link_to "Cancel", '#', class: 'btn', data: { dismiss: 'modal' } %>
			</div>
		<% end %>
	

app/views/categories/_new.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 class="form-title">Add Tags</h2>
		</div>
		<%= render "form" %>
	</div>
</div>	
		

app/views/categories/create.js.erb
$("ul.errors").html("")
<% if @category.errors.any? %>
	<% @category.errors.full_messages.each do |msg| %>
		$("ul.errors").append($("<li />").html("<%= msg.html_safe %>"))
	<% end %>
<% else %>
$("select").append("<option selected value='<%= @category.id%>'><%= @category.title %></option>")
	
	$("#category").append("<%= j render @category%>")
	$("#category-modal").modal("hide")
<% end %>

app/views/categories/delete.js.erb
$("#category-modal").html("<%= escape_javascript(render 'delete') %>")
$("#category-modal").modal("show")

app/views/categories/destroy.js.erb
$('#category-<%= @category.id %>').fadeOut(500);
$("#category-modal").modal("hide")
$(window.location.replace("/categories"))

app/views/categories/edit.js.erb
$("#category-modal").html("<%= escape_javascript(render 'edit') %>")
$("#category-modal").modal("show")

app/views/categories/index.html.erb
<% provide(:title, "Tags") %>
<div class="container">
	<div class="expense table-margin">
	<br/>
		<%= link_to "Add Tag", new_category_path, 
				remote: true, class: 'btn sign-up' %>

	
	<br/>

	<table id="category"  class="table table-bordered table-striped">
		<thead>
			<tr>
				<td>Title</td>
				<td>No. of  Income Transaction</td>
				<td>No. of  expense Transaction</td>
				<td colspan="2">action</td>
			</tr>
		</thead>

		<tbody class="category-index">
			<%#= render 'index' %>
			<div id="ajax">
				<% @categories.each do |category| %>
					<tr id="category-<%= category.id%>">
						<td><%= link_to category.title, category_path(category) %></td>
						<td><%= category.incomes.count %></td>
						<td><%= category.expenses.count %></td>
						
						<td><%= link_to "Edit", edit_category_path(category), 
										remote: true, class: 'btn btn-default' %></td>
						<td><%= link_to "Delete", category_delete_path(category), remote: true, class: 'btn btn-danger' %></td>
					</tr>
				<% end %>
			</div>
		</tbody>
	</table>
</div>
</div>
<div id="category-modal" class="modal fade"></div>


<!-- 
<div id="ajax">
	<%#= render :template => 'expenses/index' %>
</div> -->

app/views/categories/new.js.erb
$("#category-modal").html("<%= escape_javascript(render 'new') %>")
$("#category-modal").modal("show")

app/views/categories/show.html.erb
<% provide(:title, "Tags") %>
<div class="container">
	<div class="expense">
	<h2><%=@category.title %></h2>
	
				<%= link_to "Edit", edit_category_path(@category), 
					remote: true, class: 'btn btn-default' %>
	<%= link_to "Delete", category_delete_path(@category), remote: true, class: 'btn btn-danger' %>

	</div>
	<br/>
	<div class="new-income"></div>

	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<td>Title</td>
				<td>Tags</td>
				<td>Amount</td>
				<td>Date</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
		</thead>

		<tbody class="category-index">
			<% @category_data.each do |category| %>
			<%if category.class.table_name=="incomes"%>
				<tr >
					<td><%= category.title %></td>
					<td><%= category.category.title %></td>
					<td class="incomes-text">+ <%= category.amount  %></td>
					<td><%= category.date %></td>
					<td><%= link_to "Edit", edit_income_path(category.id), 
					remote: true, class: 'btn btn-default' %></td>
					<td><%= link_to "Delete", income_delete_path(category.id), remote: true, class: 'btn btn-danger' %></td>
				<tr>	
			<% else %>
				<tr >
					<td><%= category.title %></td>
					<td><%= category.category.title %></td>
					<td class="expenses-text">- <%= category.amount  %></td>
					<td><%= category.date %></td>
					<td><%= link_to "Edit", edit_expense_path(category.id), 
					remote: true, class: 'btn btn-default' %></td>
					<td><%= link_to "Delete", expense_delete_path(category.id), remote: true, class: 'btn btn-danger' %></td>
				</tr>
			<% end %>
	
	
</tr>
<% end %>
		</tbody>
	</table>
</div>
<div id="category-modal" class="modal fade"></div>