config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    get "delete"
  end
  get 'expenses/index'

  get 'expenses/new'

  get 'expenses/new'

  get 'expense/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'account_activations/edit'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'members#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :members do
    collection do 
      get :search
      # get :search, :action => 'search_post', :as => 'search_post'
      # get 'search/:q', :action => 'search', :as => 'search'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :incomes do 
    get "delete"
  end
  resources :expenses do 
    get "delete"
  end
  resources :categories do 
    get "delete"
  end
  resources :reminders do
   get "delete"
 end
 

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
   

  def index
    @expenses = current_member.expenses
    @expense_category = []
      Expense.select('category_id, sum(amount) as total').group('category_id').order('total desc').where(member_id: current_member.id).each do |expense| 
        category = Category.find(expense.category_id) 
        @expense_category.push([category.title.to_s,expense.total.to_i])
      end
  end

  def show
  	@expense = Expense.find(params[:id])
    # ajax for displaying expense on dashboard
    # respond_to do |format|
    #   format.html # renders show.html.erb
    #   format.js # renders show.js.erb
    # end
  end

  def new
  	@expense = Expense.new
  end  

  def create
  	@expenses = current_member.expenses
    @expense = Expense.create(expense_params.merge(member_id: current_member.id))
    # if params[:category_id].nil?
    #   @cat=Category.where("title = 'untagged'")
    #   print @cat.id
    #   print "haha"
    #    if (@cat.title =="")
    #     @category = Category.create(member_id: current_member.id, title: "untagged")
    #   end
    #     @expense = Expense.create(expense_params.merge(member_id: current_member.id, category_id: @category.id))
    # else
    #    @expense = Expense.create(expense_params.merge(member_id: current_member.id))
    # end
  end

  def edit
  	@expense = Expense.find(params[:id])
  end

  def update
  	@expenses = current_member.expenses
  	@expense = Expense.find(params[:id])
  	@expense.update_attributes(expense_params)
  end

  def delete
  	@expense = Expense.find(params[:expense_id])
  end

  def destroy
  	@expense = Expense.find(params[:id])
  	@expense.destroy
  end


  private 
  	def expense_params
  		params.require(:expense).permit(:title, :description, :amount, :date, :category_id).merge(member_id: current_member.id)
  	end
   
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_delete.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h3>Delete Expense</h3>
		</div>

		<div class="modal-body">
			<ul class="errors"></ul>
			Are you sure you want to delete <b><%= @expense.title  %></b>
		</div>

		<div class="modal-footer">
			<%= link_to "Yes, Delete This Expense", expense_path(@expense), method: :delete, remote: true, class: 'btn btn-danger' %>
			<%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
		</div>
	</div>
</div>

app/views/expenses/_edit.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h3><%= "Editing #{@expense.title}" %></h3>
		</div>
		<%= render "form" %>
	</div>
</div>	
		

app/views/expenses/_expense.html.erb
<tr id="expense-<%= expense.id%>">
	<td><%= expense.title %></td>
	<!-- <td><%= expense.description %></td> -->
	<td><%= expense.category.title %></td>
	<td class="expenses-text" >- <%=number_with_delimiter(expense.amount, :delimiter => ',')  %></td>
	<td><%= expense.date %></td>
	<td><%= link_to "Edit", edit_expense_path(expense), 
					remote: true, class: 'btn btn-default' %></td>
	<td><%= link_to "Delete", expense_delete_path(expense), remote: true, class: 'btn btn-danger' %></td>
</tr>

app/views/expenses/_form.html.erb
		<%= form_for @expense, remote: true, html: { style: "display:inline" } do |f| %>
			<div class="modal-body">
				<ul class="errors"></ul>
			

				<%= f.hidden_field :member_id, :value => @expense.member_id %>
			
				<div class="form-group">
					<%= f.label :title, class: 'control-label' %>
					<%= f.text_field :title, class: 'form-control' %>
				</div>

				<div class="form-group">
					<%= f.label :description, class: 'control-label' %>
					<%= f.text_field :description, class: 'form-control' %>
				</div>

				<div class="form-group col-md-6">
					<%= f.label :amount, class: 'control-label' %>
					<%= f.text_field :amount, class: 'form-control' %>
				</div>
				<div class="form-group col-md-6">
					<%= f.label :TAGS, class: 'control-label' %>

					<%= f.collection_select :category_id, current_member.categories.all, :id, :title, class: 'form-control' %>
				<%= link_to "Add Tag", new_category_path, 
				remote: true, class: 'btn sign-up' %>

				</div>

				<div class="form-group">
					<%= f.label :date , class: 'control-label' %>
				</div>


				<div class="form-group">
					<div class="input-group date", data-provide="datepicker" data-date-format="yyyy/mm/dd">
							<%= f.text_field :date,:value => Time.now.strftime('%Y/%m/%d')  %>
						<div class="input-group-addon">
							<span class="glyphicon glyphicon-th"></span>
						</div>
					</div>
				</div>
			</div>

			<div class="modal-footer">
				<%= f.submit "Add Expense", class: 'btn sign-up' %>
				<%= link_to "Cancel", '#', class: 'btn', data: { dismiss: 'modal' } %>
			</div>
		<% end %>
	

app/views/expenses/_index.html.erb
<% @expenses.each do |expense| %>
<tr>
	<td><%= expense.title %></td>
	<td><%= expense.description %></td>
	<td><%= expense.amount %></td>
	<td><%= expense.date %></td>
	<td><%= link_to "Edit", edit_expense_path(expense), 
					remote: true, class: 'btn btn-default' %></td>
	<td><%= link_to "Delete", expense_delete_path(expense), remote: true, class: 'btn btn-danger' %></td>
</tr>
<% end %>

app/views/expenses/_new.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h2 class="form-title">Add Expenses</h2>
		</div>
		<%= render "form" %>
	</div>
</div>	
		

app/views/expenses/create.js.erb
$("ul.errors").html("")
<% if @expense.errors.any? %>
	<% @expense.errors.full_messages.each do |msg| %>
		$("ul.errors").append($("<li />").html("<%= msg.html_safe %>"))
	<% end %>
<% else %>

var total =$("h3.total_expense").text();
	 
	 		if (total != "") {
	 			  location.reload();
	 		}
	 
	$("#expense").append("<%= j render @expense%>")
	$("#expense-modal").modal("hide")
<% end %>

app/views/expenses/delete.js.erb
$("#expense-modal").html("<%= escape_javascript(render 'delete') %>")
$("#expense-modal").modal("show")

app/views/expenses/destroy.js.erb
$('#expense-<%= @expense.id %>').fadeOut(500);
	$("#expense-modal").modal("hide")

app/views/expenses/edit.js.erb
$("#expense-modal").html("<%= escape_javascript(render 'edit') %>")
$("#expense-modal").modal("show")

app/views/expenses/index.html.erb
<% provide(:title, "Expenses") %>
<div class="container">
	<div class="expense table-margin">
	<br/>
		<%= link_to "Add Expense", new_expense_path, 
				remote: true, class: 'btn sign-up' %>

	<br/>
		<div id="pie" style="height: 400px"></div>
	
	<table id="expense" class="table table-bordered table-striped">
		<thead>
			<tr>
				<td>Title</td>
				<!-- <td>Description</td> -->
				<td>Tags</td>
				<td>Amount</td>
				<td>Date</td>
			<th colspan="2">Action</th>
			</tr>
		</thead>

		<tbody class="expense-index">
			<% @expenses.each do |expense| %>
				<tr id="expense-<%= expense.id%>">
					<td><%= expense.title %></td>
					<!-- <td><%= expense.description %></td> -->
					<td><%= expense.category.title %></td>
					<td class="expenses-text" >- <%=number_with_delimiter(expense.amount, :delimiter => ',')  %></td>
					<td><%= expense.date %></td>
					<td><%= link_to "Edit", edit_expense_path(expense), 
									remote: true, class: 'btn btn-default' %></td>
					<td><%= link_to "Delete", expense_delete_path(expense), remote: true, class: 'btn btn-danger' %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
</div>
<div id="expense-modal" class="modal fade"></div>


<!-- 
<div id="ajax">
	<%#= render :template => 'expenses/index' %>
</div> -->



<script type="text/javascript">

// for(var i = 0; i < bar.length; i++) {
//     var bar= bar[i];
//     for(var j = 0; j < bar.length; j++) {
//         alert(typeof("bar" + i + "][" + j + "] = " + bar[j]));
//     }
// }
// alert(bar);
	Highcharts.chart('pie', {
    chart: {
        type: 'pie',
        options3d: {
            enabled: true,
            alpha: 45
        }
    },
    title: {
        text: 'Expenses category'
    },
    subtitle: {
        text: ''
    },
    plotOptions: {
        pie: {
            innerSize: 100,
            depth: 45
        }
    },
<% a = 'Banasssssnas'.to_i%>
<% b = 5 %>
    series: [{
        name: 'Delivered amount',
        data: [<% @expense_category.each do |x,y| %>		
        ["<%= x%>",<%= y%>],
			<%end%>]
    }]
});
</script>


<%= b.class %>

app/views/expenses/new.js.erb
$("#expense-modal").html("<%= escape_javascript(render 'new') %>")
$("#expense-modal").modal("show")

app/views/expenses/update.js.erb
$("ul.errors").html("")
<% if @expense.errors.any? %>
	<% @expense.errors.full_messages.each do |msg| %>
		$("ul.errors").append($("<li />").html("<%= msg.html_safe %>"))
	<% end %>
<% else %>
	
	$('#expense-<%= @expense.id %>').replaceWith('<%= j render(@expense) %>') 
	$("#expense-modal").modal("hide")
<% end %>