config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    get "delete"
  end
  get 'expenses/index'

  get 'expenses/new'

  get 'expenses/new'

  get 'expense/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'account_activations/edit'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'members#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :members do
    collection do 
      get :search
      # get :search, :action => 'search_post', :as => 'search_post'
      # get 'search/:q', :action => 'search', :as => 'search'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :incomes do 
    get "delete"
  end
  resources :expenses do 
    get "delete"
  end
  resources :categories do 
    get "delete"
  end
  resources :reminders do
   get "delete"
 end
 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="container">
	<div class="row">
	<!-- 	<div class="col-md-6">
			<h3>Company</h3>
			<ul>
				<li><%= link_to "Home", '#' %></li>
				<li><%= link_to "Help", '#' %></li>
				<li><%= link_to "About", '#' %></li>
				 <li><%= link_to "Terms & Privacy", '#' %></li> 
				<li><%= link_to "Contact", '#' %></li>
			</ul>
		</div> -->

		<!-- <div class="col-md-6"> -->
			<!-- <h3>Subscribe!</h3> -->
			<!-- <form action="#" method="get"> -->
				<!-- <input type="email" placeholder="Enter valid email address">
				<input type="submit" value="Subscribe"> -->
				<!-- <div class="input-group"> -->
					<!-- <input type="text" class="form-control" placeholder="Enter valid email address"> -->
					<!-- <div class="input-group-btn"> -->
						<!-- <input type="submit" value="Subscribe" class="btn btn-primary"> -->
					<!-- </div> -->
				<!-- </div> -->
			<!-- </form> -->
		<!-- </div> -->

	</div>
	</div>


	<div class="copy-right navbar-fixed-bottom" >
		<p class="center">© 2017 IBINFOTECH.</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in? %>
	
	<div class="cd-main-header" style="width: 100% !important;">
		<%= link_to "Expense Analytics", root_path, class: 'navbar-brand page-scroll logo' %>
		
		<div class="cd-search is-hidden">
			<form action="/members/search" data-remote="true" method="GET">
				<input autocomplete="off" type="search" placeholder="Search..." name="search" id="search"/>
				<div class="searchResults" style="color: white;">
     			 
			</div>
			</form>
			
    		
		</div> <!-- cd-search -->
		

		

		<a href="#0" class="cd-nav-trigger"><span></span></a>



		<nav class="cd-nav">


			<ul class="cd-top-nav">
				

				<li class="has-children children add">
							<%= link_to "<i class='fa fa-plus' aria-hidden='true'></i> ".html_safe, "#0", 
				remote: true %>
							
							<ul>
								<li><%= link_to "INCOME", new_income_path,remote: true, class: "sign-up" %></li>
								<li><%= link_to "EXPENSE", new_expense_path,remote: true, class: "sign-up" %></li>	
								<li><%= link_to "REMINDER", new_reminder_path,remote: true, class: "sign-up" %></li>								
							</ul>
						</li>
				
				<li class="children-li"><%= link_to "<i class=' fa fa-download ' aria-hidden='true'></i> ".html_safe, '#', onclick: "printDiv('chart')" %></li>
				

						<% if current_member.admin? %>
							<li class="children-li"><%= link_to "Members", members_path %></li>
						<% end %>
						<li class="has-children children  account">
							<a href="#0"><%= image_tag("cd-avatar.png") %>Account</a>
							<ul>
								<li><%= link_to "Profile", current_member, class: "sign-up" %></li>
								<li><%= link_to "Settings", edit_member_path(current_member), class: "sign-up" %></li>
								<li class="divider"></li>
								<li><%= link_to "Log out", logout_path, method: "delete", class: "sign-up" %></li>
							</ul>
						</li>


				
			</ul>
		</nav>
	</div> <!-- .cd-main-header -->
<% else %>


  <nav class="navbar navbar-inverse offline-menu" style="border-radius: 0px !important; background: #1985a1;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <%= link_to "Expense Analytics", root_path, class: 'navbar-brand page-scroll logo' %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
         <!-- <li><%= link_to '<i class="fa fa-sign-up"></i>'.html_safe.concat("Sign Up"),signup_path%></li> -->
    <li><%= link_to '<i class="fa fa-sign-in"></i>'.html_safe.concat("Log In"), login_path %></li>
      </ul>
    </div>
  </div>
</nav>

<% end %>
			<script type="text/javascript">
	$("#search").on("keyup", function (e) {
		var search_value = $("#search").val();
		if (search_value != "") {
			$('form').submit();
		}else{
			$(".searchResults").hide();
			
		}
    	
    	
        // }
});
</script>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
</script>
[endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <meta charset="utf-8">
     <!-- <link rel='icon' href='/assets/favicon.ico?v=5' type='image/x-icon' /> -->
     <%= favicon_link_tag 'another_image.ico' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- <script src="http://code.highcharts.com/highcharts.js"></script> -->
<!-- <script src="https://code.highcharts.com/highcharts-3d.js"></script> -->
<!-- <script src="https://code.highcharts.com/modules/exporting.js"></script> -->

    </head>

  <%= render 'layouts/shim' %>
  <!-- Including Highcharts and Framework -->
<!-- <body>

		<div class="container">
				<%#= render 'layouts/header' %>

				<%# flash.each do |message_type, message| %>
					<div class="alert alert-<%#= message_type %>"><%#= message %></div>
				<%# end %>
				<%#= yield %>	

				<%#= render 'layouts/footer' %>
		</div>

</body> -->
<body id="page-top" <%= "data-no-turbolinks='true'".html_safe if controller_name=="members" && action_name=="show" %>>
<%= render 'layouts/header' %>	
<% if logged_in? %>
	<main class="cd-main-content">
		<nav class="cd-side-nav">
			<ul>
				<li class="cd-label">Main</li>
				<li><%= link_to "Dashboard", root_path %></li>
				<li class="has-children overview">
					<a href="#">Reports</a>
					
					<ul>
						<li><%= link_to "Expense", expenses_path, class: "btn btn-small sign-up" %></li>
						<li><%= link_to "Income", incomes_path, class: "btn btn-small sign-up" %></li>
					</ul>
				</li>
				<li class="has-children overview">
					<a href="#">Reminders</a>
					<ul>
						<li><%= link_to "View Reminders", reminders_path, class: "btn btn-small sign-up" %></li>
						<li><%= link_to "Add Reminder",new_reminder_path(@reminder),remote: true, class: "btn btn-small sign-up" %></li>
					</ul>
				</li>
				<li class="has-children overview">
					<%= link_to "TAGS", categories_path%>
					<ul>
						<% current_member.categories.each do |category| %>
							<li><%= link_to category.title, category_path(category.id)%></li>
						<% end %>
						<li><%= link_to "Add Tags",  new_category_path,remote: true, class: "btn btn-small sign-up" %></li>
					</ul>
				</li>
				<li class="has-children notifications active">
					<a href="#0">Notifications<span class="count">3</span></a>
					
					<ul>
						<li><a href="#0">All Notifications</a></li>
						<li><a href="#0">Reminder</a></li>
						<li><a href="#0">Other</a></li>
					</ul>
				</li>

				<li class="has-children comments">
					<!-- <a href="#0">Comments</a> -->
					
					<ul>
						<li><a href="#0">All Comments</a></li>
						<li><a href="#0">Edit Comment</a></li>
						<li><a href="#0">Delete Comment</a></li>
					</ul>
				</li>
			</ul>

			<ul>
				<li class="cd-label">Secondary</li>
				<li class="has-children users">
					<a href="#0">Contacts</a>
					
					<ul>
						<li><%= link_to "Add Contact", new_contact_path, remote:true %></li>
						<li><%= link_to "View Contact", contacts_path %></li>
						<li><a href="#0">Add User</a></li>
					</ul>
				</li>
				<!-- <li class="has-children bookmarks">
					<a href="#0">Bookmarks</a>
					
					<ul>
						<li><a href="#0">All Bookmarks</a></li>
						<li><a href="#0">Edit Bookmark</a></li>
						<li><a href="#0">Import Bookmark</a></li>
					</ul>
				</li> -->
				<!-- <li class="has-children images">
					<a href="#0">Images</a>
					
					<ul>
						<li><a href="#0">All Images</a></li>
						<li><a href="#0">Edit Image</a></li>
					</ul>
				</li> -->

				<li class="has-children users">
					<a href="#0">Users</a>
					
					<ul>
						<li><%= link_to "All Users", members_path %></li>
						<li><a href="#0">Edit User</a></li>
						<li><a href="#0">Add User</a></li>
					</ul>
				</li>
			</ul>

			<!-- <ul>
				<li class="cd-label">Action</li>
				<li class="action-btn"><a href="#0">+ Button</a></li>
			</ul> -->
		</nav>
		<% end %>


		<div class="content-wrapper">
				
		<% if notice %>
			<div id="notice_wrapper">
				<p class="notice"><%= notice %></p>
			</div>
		<% elsif alert %>
			<div id="notice_wrapper">
			<p class="alert"><%= alert %></p>
			</div>
		<% end %>
		
			<% flash.each do |message_type, message| %>
				<div class="alert-<%= message_type %>">
					<% if message %>
						<div id="notice_wrapper">
							<p class="notice"><%= message %></p>
						</div>
					<% end %>
				</div>
			<% end %>
		<%= yield %>

<div id="expense-modal" class="modal fade"></div>
<div id="reminder-modal" class="modal fade"></div>
<div id="income-modal" class="modal fade"></div>
<div id="contact-modal" class="modal fade"></div>
<div id="category-modal" class="modal fade"></div>
		<%if !logged_in? %>
		<%= render 'layouts/footer' %>
		<% end %>
		</div> <!-- .content-wrapper -->
		
	</main> <!-- .cd-main-content -->








			
	



	
  

<body>
 

 
</body>
</html>

app/views/layouts/header.html.erb
<nav id="mainNav" class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<div class="navbar-header" data-no-turbolink >
        <a class="navbar-brand" href="/en"><strong>nb</strong>infotech</a>
        </div>
				<%= link_to "Expense Analytics", root_path, class: 'navbar-brand page-scroll' %>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "<i class='fa fa-plus fa-2x' aria-hidden='true'></i> ".html_safe, '#'%></li>
				<li><%= link_to "<i class='fa fa-download fa-2x' aria-hidden='true'></i> ".html_safe, '#', onclick: "printDiv('chart')" %></li>
					<% if logged_in? %>
						<% if current_member.admin? %>
							<li><%= link_to "Members", members_path %></li>
						<% end %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_member %></li>
								<li><%= link_to "Settings", edit_member_path(current_member) %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "Log out", logout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li>
							<%= link_to "Sign Up", signup_path, class: 'page-scroll'	%>
						</li>
						<li>
							<%= link_to '<i class="fa fa-sign-in"></i>'.html_safe.concat("Log In"), login_path %>
						</li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>

app/views/layouts/index.html.erb
<!doctype html>
<html lang="en" class="no-js">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="css/reset.css"> <!-- CSS reset -->
	<link rel="stylesheet" href="css/style.css"> <!-- Resource style -->
	<script src="js/modernizr.js"></script> <!-- Modernizr -->
  	
	<title>Responsive Sidebar Navigation | CodyHouse</title>
</head>
<body>
	<header class="cd-main-header">
		<a href="#0" class="cd-logo"><img src="img/cd-logo.svg" alt="Logo"></a>
		
		<div class="cd-search is-hidden">
			<form action="#0">
				<input type="search" placeholder="Search...">
			</form>
		</div> <!-- cd-search -->

		<a href="#0" class="cd-nav-trigger">Menu<span></span></a>

		<nav class="cd-nav">
			<ul class="cd-top-nav">
				<li><a href="#0">Tour</a></li>
				<li><a href="#0">Support</a></li>
				<li class="has-children account">
					<a href="#0">
						<img src="img/cd-avatar.png" alt="avatar">
						Account
					</a>

					<ul>

						<li><a href="#0">My Account</a></li>
						<li><a href="#0">Edit Account</a></li>
						<li><a href="#0">Logout</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</header> <!-- .cd-main-header -->

	<main class="cd-main-content">
		<nav class="cd-side-nav">
			<ul>
				<li class="cd-label">Main</li>
				<li class="has-children overview">
					<a href="#0">Overview</a>
					
					<ul>
						<li><a href="#0">All Data</a></li>
						<li><a href="#0">Category 1</a></li>
						<li><a href="#0">Category 2</a></li>
					</ul>
				</li>
				<li class="has-children notifications active">
					<a href="#0">Notifications<span class="count">3</span></a>
					
					<ul>
						<li><a href="#0">All Notifications</a></li>
						<li><a href="#0">Friends</a></li>
						<li><a href="#0">Other</a></li>
					</ul>
				</li>

				<li class="has-children comments">
					<a href="#0">Comments</a>
					
					<ul>
						<li><a href="#0">All Comments</a></li>
						<li><a href="#0">Edit Comment</a></li>
						<li><a href="#0">Delete Comment</a></li>
					</ul>
				</li>
			</ul>

			<ul>
				<li class="cd-label">Secondary</li>
				<li class="has-children bookmarks">
					<a href="#0">Bookmarks</a>
					
					<ul>
						<li><a href="#0">All Bookmarks</a></li>
						<li><a href="#0">Edit Bookmark</a></li>
						<li><a href="#0">Import Bookmark</a></li>
					</ul>
				</li>
				<li class="has-children images">
					<a href="#0">Images</a>
					
					<ul>
						<li><a href="#0">All Images</a></li>
						<li><a href="#0">Edit Image</a></li>
					</ul>
				</li>

				<li class="has-children users">
					<a href="#0">Users</a>
					
					<ul>
						<li><a href="#0">All Users</a></li>
						<li><a href="#0">Edit User</a></li>
						<li><a href="#0">Add User</a></li>
					</ul>
				</li>
			</ul>

			<ul>
				<li class="cd-label">Action</li>
				<li class="action-btn"><a href="#0">+ Button</a></li>
			</ul>
		</nav>

		<div class="content-wrapper">
			<h1>Responsive Sidebar Navigation</h1>
		</div> <!-- .content-wrapper -->
	</main> <!-- .cd-main-content -->
<script src="js/jquery-2.1.4.js"></script>
<script src="js/jquery.menu-aim.js"></script>
<script src="js/main.js"></script> <!-- Resource jQuery -->
</body>
</html>