config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    get "delete"
  end
  get 'expenses/index'

  get 'expenses/new'

  get 'expenses/new'

  get 'expense/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'account_activations/edit'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'members#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :members do
    collection do 
      get :search
      # get :search, :action => 'search_post', :as => 'search_post'
      # get 'search/:q', :action => 'search', :as => 'search'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :incomes do 
    get "delete"
  end
  resources :expenses do 
    get "delete"
  end
  resources :categories do 
    get "delete"
  end
  resources :reminders do
   get "delete"
 end
 

end

app/models/member.rb
class Member < ActiveRecord::Base
	has_many :incomes, dependent: :destroy
	has_many :contacts, dependent: :destroy
	has_many :expenses
	has_many :reminders
	has_many :categories
	attr_accessor :remember_token, :activation_token, :reset_token
	before_save :downcase_email
	before_create :create_activation_digest
	validates :member_name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :member_email, presence: true, length: { maximum: 255 },
														format: { with: VALID_EMAIL_REGEX },
														uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }, allow_blank: true
	validates :accept, acceptance: { accept: 'yes' }
	validates :member_country, presence: true

	# Returns the hash digest of the given string.
	def Member.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :																							BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a Random Token.
	def Member.new_token
		SecureRandom.urlsafe_base64
	end

	# Remembers a user in the database for use in persistent sessions.
	def remember
		self.remember_token = Member.new_token
		update_attribute(:remember_digest, Member.digest(remember_token))
	end

	# Returns true if token matches  the digest.
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end

	# def country_name
	# 	country = ISO3166::Country[country_code]
	# 	country.translations[I18n.locale.to_s] || country.name
	# end

	# Activated an account.
	def activate
		update_attribute(:activated, true)
		update_attribute(:activated_at, Time.zone.now)
	end

	# Send activation email.
	def send_activation_email
		MemberMailer.account_activation(self).deliver_now
	end

	# Sets the password reset attributes.
	def create_reset_digest
		self.reset_token = Member.new_token
		update_attribute(:reset_digest, Member.digest(reset_token))
		update_attribute(:reset_sent_at, Time.zone.now)
	end

	# Sends password reset email.
	def send_password_reset_email
		MemberMailer.password_reset(self).deliver_now
	end

	# Returns true if a password reset has expired.
	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end

	private	

		# Converts email to all lower case.
		def downcase_email
			self.member_email = member_email.downcase
		end

		# Creates and assigns the activation token and digest.
		def create_activation_digest
			self.activation_token = Member.new_token
			self.activation_digest = Member.digest(activation_token)
		end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :logged_in_member, only: [:show, :index, :edit, :update, :destroy]
  before_action :correct_member, only: [:edit, :update]
  before_action :admin_member, only: :destroy

  def index
    # @members = Member.all
    redirect_to '/' unless current_member.admin?
    @members = Member.all.paginate(page: params[:page])
  end

  def show
    # @income = Member.incomes
    if params[:date]
      if params[:date].to_i ==4 
        
      elsif params[:date].to_i ==1
        @week = "THIS WEEK"
      elsif params[:date].to_i ==2
        @week = "LAST WEEK"
      else
        @week = "LAST MONTH"
      end
      @date = params[:date].to_i.weeks.ago
    else
      @week = "THIS MONTH"
      @date = 4.weeks.ago
    end

    @transaction=(current_member.expenses.all + current_member.incomes.all).sort{|a,b| b.date <=> a.date }
    
    if params[:id] == current_member.id.to_s
      @total = current_member.incomes.sum(:amount) - current_member.expenses.sum(:amount)
      @member = Member.find(params[:id])
      @income = current_member.incomes
      @expense = current_member.expenses
    else
      redirect_to root_url
    end
    # For pagination
    @reminders = current_member.reminders.paginate(:page => 1, :per_page => 2)
  end

  def search
    search =  params[:search]
    @expense=Expense.where('title LIKE ?', "%#{search}%")
    @income=Income.where('title LIKE ?', "%#{search}%")
    @category= Category.where('title LIKE ?', "%#{search}%")
    @search = @expense + @income + @category  
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      @member.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    Member.find(params[:id]).destroy
    flash[:success] = "Member deleted"
    redirect_to members_url
  end

  def edit
    # @member = Member.find(params[:id])
  end

  def update
    # @member = Member.find(params[:id])
    if @member.update_attributes(member_params)
      # Handle a successful update.
      flash[:success] = "Profile Updated"
      redirect_to @member
    else
      render 'edit'
    end
  end

  private
    def member_params
      params.require(:member).permit(:member_name, :member_email, :member_country, :password, :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in member.
    def logged_in_member
      unless logged_in?
        store_location
        flash[:danger] = "Please Log In"
        redirect_to login_url
      end
    end

    #Confirms the correct member.
    def correct_member
      @member = Member.find(params[:id])
      redirect_to(root_url) unless current_member?(@member)
    end

    # Confirms an admin member.
    def admin_member
      redirect_to(root_url) unless current_member.admin?
    end
end

app/helpers/members_helper.rb
module MembersHelper

	# Returns the gravatar for the given user.
	def gravatar_for(member, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(current_member.member_email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: current_member.member_name, class: "gravatar img-circle")
	end

end

app/views/members/_member.html.erb
<li>
	<%= gravatar_for member, size: 50 %>
	<%= link_to member.member_name, member %>
	<% if current_member.admin? && !current_member?(member) %> | <%= link_to "delete", member, method: :delete,
																	data: { Confirm: "You Sure?" } %>
	<% end %>
</li>

app/views/members/_search.html.erb
<ul>
<% @search.each do |search|%>
<li><%=search.class.table_name %></li>
	<li><%= search.title%></li>

<% end %>
</ul>

app/views/members/_test.html.erb
<p>test data</p>

app/views/members/edit.html.erb
<% provide(:title, "Edit Member") %>
<div class="container">


<div class="row">
	<div class="col-md-6">
	<h1 class="form-title">Update your profile</h1> 
		<%= form_for(@member) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :member_name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.text_field :member_email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.label :country_code, "Country" %>
			<%= f.country_select :member_country, prompt: "Select a Country" %>

			<%= f.submit "Update Changes", class: 'btn sign-up' %>
		<% end %>

		<div class="gravatar_edit">
			<%= gravatar_for @member %>
			
			<a href="http://gravatar.com/emails">Change</a>
		</div>
	</div>
</div>
</div>

app/views/members/index.html.erb
<% provide(:title, "All member") %>


<%= will_paginate %>

<ul class="members">
<h2>All members</h2>
	<%= render @members %>
</ul>

<%= will_paginate %>

app/views/members/new.html.erb
<% provide(:title, "Sign Up") %>
<div class="container">


<div class="row">
	<div class="col col-md-6 col-md-offset-3">
	<h1 class="form-title">Sign Up</h1>
		<%= form_for(@member) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :member_name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.text_field :member_email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<!-- <div class="form-group">
				<%#= f.label :country, :class => "col-md-3 control-label" %>
				<div class="col-md-9">
					<%#= f.country_select :member_country, ["Nepal"], {}, { :class => "form-control" } %>
				</div>
			</div> -->

			<%= f.label :country_code, "Country" %>
			<%= f.country_select :member_country, prompt: "Select a country" %>

			<!-- <div> -->
			<!-- check_box_tag 'accept', class: "checkbox" -->
			<!-- <span>I agree to the Terms and Conditions.</span> -->
			<!-- </div> -->

			<%= f.submit "Sign up", class: "btn sign-up" %>
		<% end %>
	</div>
</div>
</div>

app/views/members/search.js.erb
$(".searchResults").html("<%= j render 'members/search' %>");
$(".searchResults").show();

app/views/members/show.html.erb
<% provide(:title, current_member.member_name) %>
<div class="container">
<div class="row" data-no-turbolink="true" >
    <!-- <aside class="col-md-4"> -->
        <!-- <section class="user_info"> -->
            <!-- <h1> -->
                <!-- <p><%= gravatar_for @member %></p> -->
                <!-- Check alternative later. -->
                <!-- <br><br><br><br><br> -->
                <!-- <p>Name: <%= @member.member_name %></p> -->
                <!-- <p>Email: <%= @member.member_email %></p> -->
                <!-- <p>Country: <%= @member.member_country %></p> -->
                <!-- <p>Month's Saving: </p> -->
            <!-- </h1> -->


            <!-- Check alternative later. -->
            <!-- <br><br><br><br><br><br> -->
            <!-- <p>Money Left: <%= link_to("Add Income", '#') %></p> -->

            
            <!-- Check for alternative -->
            <!-- <br><br><br><br> -->
            <!-- <p><%= link_to "Edit my profile", edit_member_path(current_member), :style => "color: white;"%></p> -->
        <!-- </section> -->
    <!-- </aside> -->
    <!-- <div class="col-md-12"> -->
    <br/>
        <div class="income">
       <style> 
       .show-date{

        position: absolute !important;
        top: 100 !important;
        right: 350 !important;
       }</style>
       
        
            <%= link_to "Expenses", expenses_path, class: "btn btn-small sign-up" %>
            <%= link_to "Incomes", incomes_path, class: "btn btn-small sign-up" %>
            <%= link_to "Reminders", reminders_path, class: "btn btn-small sign-up" %>
            <%= link_to "Tags", '#', class: "btn btn-small sign-up" %>
              <%= link_to "<i class='fa fa-calendar' aria-hidden='true'></i> THIS WEEK <i class='fa fa-arrow-down' aria-hidden='true'></i> ".html_safe, "#0", 
                remote: true, class: "btn btn-small sign-up" %>
           <!-- <li class="has-children children add"> -->
                          
    <!-- <div class="show-date"> -->
        <!-- <nav class="cd-nav"> -->
            <ul class="cd-top-nav btn btn-small sign-up">
            <li class="has-children children show">
                            <%= link_to"<i class='fa fa-calendar' aria-hidden='true'></i> #{@week} <i class='fa fa-arrow-down' aria-hidden='true'></i> ".html_safe, "#0", 
                remote: true %>
                            
                            <ul>
                                <li><%= link_to "THIS WEEK", member_path(current_member, date: 1), class: "sign-up" %></li>
                                <li><%= link_to "LAST WEEK", member_path(current_member, date: 2), class: "sign-up" %></li>
                                <li><%= link_to "THIS MONTH", member_path(current_member, date: 4), class: "sign-up" %></li>
                                <li><%= link_to "LAST MONTH", member_path(current_member, date: 8), class: "sign-up" %></li>

                                                                
                            </ul>
                        </li>
                        </ul>
                    <!-- </nav> -->
    <!-- </div> -->
       <!-- </li>     -->
        </div>
        <br />

     
        <table class="table ">
            <thead>
                <th><%= "net worth".upcase %></th>
                <th><%= "income".upcase %></th>
                <th><%= "expense".upcase %></th>
            </thead>
            <tbody>
                <tr>
                    <% if @total < 0 %>
                        <td style = "color: red;"><h3><%= number_with_delimiter(@total, :delimiter => ',') %></h3></td>
                    <% else %>
                        <td style = "color: green;"><h3>+<%= number_with_delimiter(@total, :delimiter => ',') %></h3></td>
                    <% end %>

                    
                    <td style = "color: green"><h3 class="total_income">+<%= number_with_delimiter(current_member.incomes.sum(:amount), :delimiter => ",") %></h3></td>
                    <td style = "color: red"><h3 class="total_expense">-<%= number_with_delimiter(current_member.expenses.sum(:amount), :delimiter => ",") %></h3></td>
                </tr>
            </tbody>
        </table>
        <!-- <div class="container"> -->
            <!-- <div class="test" id="new_test">

            </div> -->
            <div class="" id="chart">
                <div class="col-xs-6 col-sm-6" id="printChart" style="height: 400px; width: 40vw;"></div>
                <div class="col-xs-6 col-sm-6" id="pieChart" style="height: 400px; width: 40vw;"></div>
            </div>

            
        <!-- </div> -->
        <%= link_to "<i class='glyphicon glyphicon-print'></i> Print this chart".html_safe, '#', onclick: "printDiv('chart')" %>
        <hr />


<div class="col-md-12 col-xs-10">
        <div class="transaction table-margin">
            <span><h3>Transaction</h3> 
            </span>
        <!-- <br /> -->
        <%#= will_paginate @reminders %>
            <table id="transaction" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Tags</th>
                    <th>Amount</th>
                    <th>Date</th>
                    <th colspan="2">Action</th>
                </tr>
            </thead>

            <tbody class="income-index">
                <% @transaction.each do |transaction| %>
                <%if transaction.class.table_name=="incomes"%>
                    <tr id="income-<%= transaction.id %>">
                    <% else %>
                    <tr id="expense-<%= transaction.id %>">
                    <% end %>
                        <td><%= transaction.title %></td>
                        <td><%= transaction.category.title %></td>
                        
                        <%if transaction.class.table_name=="incomes"%>
                            <td class="incomes-text">+ <%= number_with_delimiter(transaction.amount, :delimiter => ',')   %></td>
                            <td><%= transaction.date %></td>
                        
                    <td><%= link_to "Edit", edit_income_path(transaction), 
                                    remote: true, class: 'btn btn-default ' %></td>
                    <td><%= link_to "Delete", income_delete_path(transaction), remote: true, class: 'btn btn-danger ' %></td>
                        <% else %>
                             <td class="expenses-text">- <%= number_with_delimiter(transaction.amount, :delimiter => ',')  %></td>
                                                     <td><%= transaction.date %></td>
                        
                    <td><%= link_to "Edit", edit_expense_path(transaction), 
                                    remote: true, class: 'btn btn-default ' %></td>
                    <td><%= link_to "Delete", expense_delete_path(transaction), remote: true, class: 'btn btn-danger ' %></td>
                         <% end %>
                        
                    </tr>
                <% end %>
            </tbody>
            </table>
        </div>
</div>
</div>
</div>
<!-- </div> -->
<!-- Javascript for running chart (Line chart and PieChart) -->
<script>
    $(document).ready(function () {
    $('#printChart').highcharts({
        chart: {
            type: 'line'
            
        },
        title: {
            text: 'Expenses and Incomes'
        },
        credits: {
            enabled: false
        },
        subtitle: {
            text: 'Source: ExpenseAnalytics.com'
        },
        xAxis: {

            type: 'datetime',
            
        },

        yAxis: {
            title: {
                text: 'Currency'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true

                    
                },marker: {
                    enabled: false
        },
                enableMouseTracking: true,

            }
        },
        series: [{
                    pointInterval: <%= 1.day * 1000 %>,
                    pointStart: <%= @date.to_i * 1000%>,
                    name: 'Income',color: 'green',
                        data: <%= (@date.to_date..Date.today).map{|date| @income.total_on(date).to_f}.inspect%>
                    },
                    {
                        pointInterval: <%= 1.day * 1000 %>,
                    pointStart: <%= @date.to_i * 1000%>,
                        name: 'Expenses',
                         data: <%= (@date.to_date..Date.today).map{|date| @expense.total_on(date).to_f}.inspect%>
            }]
    });
});


// For Pie-chart
$(function () {

    $(document).ready(function () {

        // Build the chart
        $('#pieChart').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            credits: {
                enabled: false
            },
            title: {
                text: 'Comparison Chart of Expense and Income'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false
                    },
                    showInLegend: true
                }
            },
            series: [{
                name: 'Analytics',
                colorByPoint: true,
                data: [{
                    name: 'Expenses',
                    y: <%= current_member.expenses.where('date >= ?', @date).sum(:amount) %>,
                    sliced: true,
                    selected: true
                }, {
                    name: 'Incomes',
                    y: <%= current_member.incomes.where('date >= ?', @date).sum(:amount) %>,
                    color: 'green'
                }]
            }]
        });
    });
});
</script>

app/views/members/show.js.erb
var content = '<%= j render 'test' %>'
$('.test').html(content);